version: '3.7'

services:
    postgres:
        image: postgres:13
        environment:
            POSTGRES_PASSWORD: "secret"
            POSTGRES_DB: "api"
        ports:
            - "5432:5432"
        networks:
            - internal
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: unless-stopped
    redis:
        image: redis:6
        ports:
            - "6379:6379"
        networks:
            - internal
        restart: unless-stopped
    app:
        restart: always
        build: .
        env_file:
            - .env
        ports:
            - "3000:3000"
        depends_on:
            - postgres
            - redis
        networks:
            - internal

networks:
    internal:
        driver: bridge
volumes:
    pgdata:
